# Generated by Django 5.2.16 on 2026-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10)),
                ('tier', models.CharField(choices=[('FREE', 'Free'), ('STARTER', 'Starter'), ('CREATOR', 'Creator'), ('PRO', 'Pro')], default='FREE', max_length=10)),
                ('profile_picture', models.URLField(blank=True, max_length=500, null=True)),
                ('posts_created', models.PositiveIntegerField(default=0)),
                ('publish_clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
