# Generated by Django 5.2.16 on 2026-08-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adminauditlog_adminpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='disabled_reason',
            field=models.TextField(blank=True),
        ),
    ]
