# Generated by Django 5.2.16 on 2026-08-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langgraph_orchestrator', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_posts', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='postvariation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='langgraph_orchestrator.generatedpost'),
        ),
    ]
