# Generated by Django 5.2.16 on 2026-07-23 17:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual Input')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
