# Generated by Django 5.2.16 on 2026-08-14 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('source_type', models.CharField(choices=[('RSS', 'RSS Feed'), ('WEBHOOK', 'Webhook'), ('MANUAL', 'Manual Input')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('input_type', models.CharField(max_length=20)),
                ('input_data', models.TextField(blank=True, null=True)),
                ('user_image_prompt', models.TextField(blank=True, null=True)),
                ('generate_image', models.BooleanField(default=True)),
                ('generated_content', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
