# Generated by Django 5.2.16 on 2026-08-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_initial'),
        ('workspaces', '0005_workspacemembership_alter_user_workspaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generation_tasks', to='workspaces.workspace'),
        ),
    ]
