# Generated by Django 5.2.16 on 2026-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_generationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='user_image_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
