# Generated by Django 5.2.16 on 2026-07-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_generationtask_user_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='generate_image',
            field=models.BooleanField(default=True),
        ),
    ]
