# Generated by Django 5.2.16 on 2026-07-25 07:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
                ('operational_procedures', models.TextField(blank=True, null=True)),
                ('is_online_or_remote', models.BooleanField(default=False)),
                ('physical_location_type', models.CharField(blank=True, max_length=100, null=True)),
                ('services_provided', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
