# Generated by Django 5.2.16 on 2026-08-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformaccount',
            name='platform',
            field=models.CharField(choices=[('FACEBOOK_PAGE', 'Facebook Page'), ('TWITTER', 'Twitter'), ('LINKEDIN', 'LinkedIn'), ('INSTAGRAM', 'Instagram'), ('PINTEREST', 'Pinterest'), ('WHATSAPP', 'WhatsApp')], max_length=50),
        ),
    ]
