# Generated by Django 5.2.16 on 2026-07-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='hugging_face_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
