# Generated by Django on 2026-08-22 12:24

from django.db import migrations

def remove_legacy_whatsapp(apps, schema_editor):
    PlatformAccount = apps.get_model('workspaces', 'PlatformAccount')
    # Do not delete to preserve SocialPost cascade history. Mark as deprecated instead.
    PlatformAccount.objects.filter(
        platform='WHATSAPP', 
        access_token='evolution_api_token'
    ).update(
        name='WhatsApp (Deprecated Evolution API)',
        access_token='deprecated_evolution_api_token'
    )

def restore_legacy_whatsapp(apps, schema_editor):
    PlatformAccount = apps.get_model('workspaces', 'PlatformAccount')
    PlatformAccount.objects.filter(
        platform='WHATSAPP', 
        access_token='deprecated_evolution_api_token'
    ).update(
        name='WhatsApp',
        access_token='evolution_api_token'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_whatsappintegration'),
    ]

    operations = [
        migrations.RunPython(remove_legacy_whatsapp, restore_legacy_whatsapp),
    ]
