# Generated by Django 5.2.16 on 2026-08-04 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_workspace_hugging_face_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='user',
            name='workspaces',
            field=models.ManyToManyField(related_name='users', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_old', to='workspaces.workspace'),
        ),
    ]
