# Generated by Django 5.2.16 on 2026-08-28 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_memberships(apps, schema_editor):
    User = apps.get_model('workspaces', 'User')
    WorkspaceMembership = apps.get_model('workspaces', 'WorkspaceMembership')
    
    with schema_editor.connection.cursor() as cursor:
        try:
            cursor.execute("SELECT user_id, workspace_id FROM workspaces_user_workspaces")
            legacy_data = cursor.fetchall()
        except Exception:
            legacy_data = []
            
    from collections import defaultdict
    workspace_users = defaultdict(list)
    for user_id, workspace_id in legacy_data:
        workspace_users[workspace_id].append(user_id)
        
    for workspace_id, user_ids in workspace_users.items():
        users = list(User.objects.filter(id__in=user_ids).order_by('date_joined'))
        for i, user in enumerate(users):
            role = 'OWNER' if i == 0 else 'MEMBER'
            WorkspaceMembership.objects.create(
                user=user,
                workspace_id=workspace_id,
                role=role,
                status='ACTIVE'
            )

class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_remove_legacy_evolution_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member'), ('VIEWER', 'Viewer')], default='MEMBER', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
        ),
        migrations.RunPython(migrate_legacy_memberships),
        migrations.RemoveField(
            model_name='user',
            name='workspaces',
        ),
        migrations.AddField(
            model_name='user',
            name='workspaces',
            field=models.ManyToManyField(related_name='users', through='workspaces.WorkspaceMembership', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user', 'status'], name='workspaces__user_id_074457_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'role'], name='workspaces__workspa_0c4683_idx'),
        ),
        migrations.AddConstraint(
            model_name='workspacemembership',
            constraint=models.UniqueConstraint(fields=('user', 'workspace'), name='unique_workspace_membership'),
        ),
    ]
