# Generated by Django 5.2.16 on 2026-08-04 16:20

from django.db import migrations


def migrate_workspaces(apps, schema_editor):
    User = apps.get_model('workspaces', 'User')
    for user in User.objects.all():
        if user.workspace:
            user.current_workspace = user.workspace
            user.workspaces.add(user.workspace)
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0004_user_current_workspace_user_workspaces_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_workspaces),
    ]
