# Generated by Django 5.2.16 on 2026-08-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0005_auto_20260804_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='workspace',
        ),
    ]
