# Generated by Django 5.2.16 on 2026-08-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0006_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=15),
        ),
    ]
