# Generated by Django 5.2.16 on 2026-08-29 11:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0007_workspace_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'name'], name='workspaces__workspa_87a885_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'name'), name='unique_workspace_role_name')],
            },
        ),
    ]
