# Generated by Django 5.2.16 on 2026-08-29 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0008_workspacerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacemembership',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='workspaces.workspacerole'),
        ),
    ]
