# Generated by Django 5.2.16 on 2026-09-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0009_workspacemembership_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platformaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='platformaccount',
            name='access_token',
            field=models.TextField(blank=True, default=''),
        ),
    ]
