# Generated by Django 5.2.16 on 2026-08-14 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_routing', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedimage',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='platform_routing.generatedimage'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='platform_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='workspaces.platformaccount'),
        ),
    ]
