# Generated by Django 5.2.16 on 2026-08-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_subscription_usagerecord'),
        ('workspaces', '0005_workspacemembership_alter_user_workspaces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='payments.plan'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='workspaces.workspace'),
        ),
    ]
